### ISSUE TITLE
Too much CPU in use

### ISSUE THREAD

**Issue by watchdog2000** [EntySec/Shreder#2]
Ive run this a few times now on a Parrot OS machine running with 8GB RAM and 8 vCPUs. Everytime it runs it freezes up my whole VM without printing anything. Perhaps could you consider allowing the user to specify how many threads they want to use to prevent this happening? Also lower the default amount of threads.

**Comment by enty8080** [comment]
@watchdog2000 Problem in your VM, it is normal for system to freeze after a lot of threads started.

**Comment by watchdog2000** [comment]
For now I’m going to customise the code myself because it does not work with some wordlists due to character encodings and also crashes my system because of too many threads. 
it’s a shame, I really wanted this to work because it looked great, but it just doesn’t. 
its not even like my system is low spec, it just freezes, my system doesn’t like it and therefore kills the process off after some time waiting.

**Comment by enty8080** [comment]
@watchdog2000 

The **encoding** error is problem in your file, not in my script. To fix this just change encoding to `utf-8`. My script uses `open()` - default python function. I can not fix YOUR problem in YOUR file.

**Comment by watchdog2000** [comment]
Every other program manages to open and read my file perfectly fine. With rockyou being one of the most popular wordlists in use I would have thought a developer would write to have it working. 
Sorry for trying to make suggestions to improve your open source project. Nothing I’ve said has been malicious, I just raised my issue and made a suggestion so users have a better time using your code.
