### ISSUE TITLE
ssh server dying

### ISSUE THREAD

**Issue by Fox085** [EntySec/Shreder#8]
In your "connect" function, paramiko try to connect to server. In my case, as server was Win10 with ssh server. After you fail password, it asks you to try password again. When I launch your code, Win10 quickly got stuck with 10+ ssh connections NOW, leading to ssh server death, and next passwords got EOF from ssh.
I suggest you to put ssh.close() in except block before return to avoid this mess
![image](https://user-images.githubusercontent.com/77167844/170870483-53fd64de-5442-42b9-b833-4272405d08e4.png)
Also, thanks for library!

**Comment by enty8080** [comment]
@Fox085 Thanks for the submittion. I have fixed this.

Now it looks like this:

```python3
except Exception:
    pass

ssh.close()
```

`pass` allows to continue function to execute and reach `ssh.close()`.
